name: Send messages

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        
      - name: Send messages
        run: |
          ./OWWeeklyReport/OWWeeklyReport/bin/Debug/net6.0/OWWeeklyReport.exe ${{ secrets.WEBHOOK }}
