name: Send messages

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        
      - name: Send messages
        run: |
          ./OWWeeklyReport/OWWeeklyReport/bin/Debug/net6.0/OWWeeklyReport.exe ${{ secrets.WEBHOOK }}
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Updated previousWeek.json"
          git push
